### ISSUE TITLE
Doc for (click) event

### ISSUE THREAD

**Issue by MicaelaLV** [jiayihu/ng-animate#1]
I'm looking for a way to attach the animation at a click event and the documentation doesn't provide any kind of assistance on that. And there's nothing online. Can you help me solve this issue?

**Comment by jiayihu** [comment]
The animation usage of the lib is like any other Angular animation and they must be triggered by a value (called state) transition. You can read more about them in the [official doc for Angular animations](https://angular.io/guide/animations#quickstart-example-transitioning-between-two-states), where there is an example of animated button on click.

Then you can also have a look at the [demo application source](https://github.com/jiayihu/ng-animate/blob/master/demo/app/app.component.html#L24), where animations are also triggered by a change of state on button click.

Let me know if you need more info.

**Comment by MicaelaLV** [comment]
Thank you very much @jiayihu
