### ISSUE TITLE
What remaining features pending to up the version to 1.0.0?

### ISSUE THREAD

**Issue by guillermoarellano** [jiayihu/ng-animate#12]
Hi, 

What are the remaining features or code enhancements needed for library be set to v1.0.0? 

Thanks,
Guillermo

**Comment by jiayihu** [comment]
It's not a matter of features but about stability. I recently updated to Angular 6 and supported AOT so I'm waiting for more projects to use the lib and see if there are any issues

**Comment by guillermoarellano** [comment]
Hi Jiayi,

Understood. I will use it on some of my live, personal projects to see if it performs well. 

FYI, when I worked with some of my bigger clients, they would refuse use of open source packages that were less than version 1.0. I applaud that you want your library battle tested before upping the version. Really gives us developers confidence in what you are producing.
