### ISSUE TITLE
Add common animations

### ISSUE THREAD

**Issue by jiayihu** [jiayihu/ng-animate#2]
So far only `animate.css` animations are available but I might add also other common animations like `height` and `width` ones.

**Comment by guillermoarellano** [comment]
Hi @jiayihu ,

I would love to help contribute to your project. Was wondering if you could help answer a few questions I have about this particular issue you've added to your GitHub. 

Can you explain and break down this enhancement request a bit further? Starting with the two animations you want to add for `height` and `width`, are these two animations also part of what the latest version of Animate.css offers? Are you trying to grow your project to be larger in scope or keep feature parity with Animate.css? Maybe you are the scope increase will encompass a collection of useful animations that serve as building blocks for entry-level interactivity enhancements to Angular web apps. 

Please let us know.

Thanks,
Guillermo

**Comment by jiayihu** [comment]
Hi @guillermoarellano , thanks for your reply to the issue! My goal is to keep feature parity with animate.css but I'd like also to add **a few** extra animations which are very common and missing from the lib.
To be specific, when I created this issue, I was thinking about [collapse](https://getbootstrap.com/docs/4.1/components/collapse/) which I use very often

**Comment by guillermoarellano** [comment]
Hi Jiayi,

I would recommend keeping the focus of the project to delivering Animate.css functionality in an Angular manner. Once you start deviating from the specified intent of the project, you will start losing the audience who want to use your library. My recommendation would be to create _recipes_ that show how people could recreate the Bootstrap's **collapse** functionality using ng-animate. Just add the information and sample code to your wiki library and let users go from there. 

Sincerely,
Guillermo

**Comment by jiayihu** [comment]
Sounds reasonable, let's keep it simple.
