### ISSUE TITLE
Add delay option

### ISSUE THREAD

**Issue by phl3x0r** [jiayihu/ng-animate#3]
Hey there.
Great work on implementing the classic animate.css for ng.
Would you consider adding support for delay as well?

Kind regards

**Comment by jiayihu** [comment]
Hi @phl3x0r,
do you mean the equivalent of `animation-delay` CSS property?

**Comment by phl3x0r** [comment]
I mean like how the timing property normally works:
https://angular.io/guide/animations#delay

**Comment by jiayihu** [comment]
Clear, it will be in the next minor release

**Comment by jiayihu** [comment]
I've added `delay` param in version `0.3.0`.
