### ISSUE TITLE
Create Ivy distribution

### ISSUE THREAD

**Issue by bjornharvold** [jiayihu/ng-animate#46]
From Angular CLI 13.x:

Processing legacy "View Engine" libraries:
- ng-animate [es2015/esm2015] (git+https://github.com/jiayihu/ng-animate.git)
- ng-animate [main/umd] (git+https://github.com/jiayihu/ng-animate.git)
Encourage the library authors to publish an Ivy distribution.

**Comment by TheDelta** [comment]
@jiayihu v2 fixes this issue as well ;)
